travis:
  secure:
    BINSTAR_TOKEN: U2wogpI2L0ibBHnDaifetRAEvmE48mnWjTzrpzUOWWcgzlq9OVPfpKDC2QT1Vcp/YQiSLXnSGc5AhYGJlmyTOfooPOjzhaDcG7m9RXhP/6V0L+HxVyFycMZQ7voYG4iiBl2clT198rLXJiCSwhwMoZnJZdT9P6vUU0384FouleBKb8wNDA1HXwPw7cOtTikqdGcethJk35oONVStVqQjv2ai08Uj2mGFuc64RFwfCEDXENPOAKNkA6B1jqhPSGcMVrynhwNaMEypRuJHztsRwY2Ur5rJODpPYZ2OTGps+ETW0KkrpCGLWqAqKTAr8v2m2sigcsoY+erCPIsKPwbMQECkExErj26TK0bekzUKyxZYYFuLZsDUqHQnEtK6rh6iN4HBrz6FWbXnX0N1YWaMAPG4hXHpp/y4xPABd2PcSqp/6HsxupS3W6ZW6UFCx5i6T6/cl+6p9cB7ihiW8YZj54j32TIYW0T6Uuc6qsy1XMwHmOZIq43lRxBrbnb1pPqv1qSJQhwBw6/LAPm5ijnhV2I3rgf+e/6DqdHxKtHbaVYljrYIDTLTxOgOCRxrg3xY60o0KLV7LjmE17bVYB6zUGII/S0vwa6EwoMvjZRws0MygwmlCCbl/9BL2+u6avSPfVstuqCfxlAl5kmbb4ooCPhoOyJUuy/Ipp/Oee0a5+Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
